#!/bin/bash

mvn clean install

if [ -z "$1" ]; then
 java -cp target/parking_lot-0.0.1-SNAPSHOT.jar com.gojek.parking_lot.ParkingLotApp <&0
else
 java -cp target/parking_lot-0.0.1-SNAPSHOT.jar com.gojek.parking_lot.ParkingLotApp $1
fi